# Generated by Django 5.1.15 on 2026-08-31 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4) for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag')),
                ('name', models.CharField(db_index=True, help_text='Amenity or feature name', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for frontend rendering', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4) for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag')),
                ('title', models.CharField(db_index=True, help_text='Listing headline / property title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed property description')),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('plot', 'Plot / Land'), ('rental', 'Rental Property'), ('industrial', 'Industrial')], db_index=True, default='residential', help_text='Category of property', max_length=30)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], db_index=True, default='sale', help_text='Listing purpose: Sale or Rent', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('under_negotiation', 'Under Negotiation'), ('sold', 'Sold'), ('rented', 'Rented'), ('off_market', 'Off Market')], db_index=True, default='available', help_text='Current transaction status', max_length=30)),
                ('address', models.CharField(help_text='Street address / House or Building Number', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City (e.g., Karachi, Lahore, Islamabad)', max_length=100)),
                ('locality', models.CharField(db_index=True, help_text='Sector, Phase, Block, or Neighborhood (e.g., DHA Phase 6, Bahria Town)', max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude coordinate for map view', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude coordinate for map view', max_digits=10, null=True)),
                ('size', models.DecimalField(decimal_places=2, help_text='Total area size value', max_digits=12)),
                ('size_unit', models.CharField(choices=[('marla', 'Marla'), ('kanal', 'Kanal'), ('sq_ft', 'Sq. Ft.'), ('sq_yd', 'Sq. Yd.'), ('acre', 'Acre')], default='marla', help_text='Measurement unit (Marla, Kanal, Sq Ft, etc.)', max_length=20)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Listing price in currency', max_digits=14)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated price per size unit', max_digits=14, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, help_text='Number of bedrooms (if residential)', null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, help_text='Number of bathrooms (if residential)', null=True)),
                ('owner_name', models.CharField(help_text='Property owner full name', max_length=200)),
                ('owner_contact', models.CharField(blank=True, db_index=True, help_text='Owner phone number / WhatsApp', max_length=50)),
                ('owner_email', models.EmailField(blank=True, help_text='Owner email address', max_length=254)),
                ('amenities', models.ManyToManyField(blank=True, help_text='Associated amenities and features', related_name='properties', to='properties.amenity')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4) for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag')),
                ('image_url', models.URLField(help_text='Public or signed URL from Supabase Storage', max_length=1000)),
                ('storage_path', models.CharField(help_text='Relative storage bucket path (e.g. properties/<id>/<filename>)', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Short description or room label', max_length=255)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Designates this image as the main cover photo')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sorting order in gallery display')),
                ('property', models.ForeignKey(help_text='Associated property listing', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['-is_primary', 'display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'price'], name='properties__status_800e45_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type', 'status'], name='properties__city_d0ae36_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'locality'], name='properties__city_23f8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type', 'status'], name='properties__listing_c2c341_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='properties__propert_6e4e30_idx'),
        ),
    ]
