# Generated by Django 5.1.15 on 2026-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Listing price in currency (manually set)', max_digits=14),
        ),
    ]
