# Generated by Django 5.1.15 on 2026-08-31 08:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4) for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag')),
                ('full_name', models.CharField(db_index=True, help_text='Full legal name of the client', max_length=200)),
                ('phone_number', models.CharField(db_index=True, help_text='Primary contact number (e.g. +92-300-1234567)', max_length=50)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Contact email address (optional)', max_length=254)),
                ('cnic', models.CharField(blank=True, db_index=True, help_text='National Identity Card Number (e.g. 42101-1234567-1)', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Residential / Business address', max_length=255)),
                ('client_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('tenant', 'Tenant'), ('landlord', 'Landlord')], db_index=True, default='buyer', help_text='Client classification within the pipeline', max_length=20)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('walk_in', 'Walk-in'), ('website', 'Website Inquiry'), ('social_media', 'Social Media (Instagram / Facebook)'), ('portal_zameen', 'Zameen.com'), ('portal_olx', 'OLX'), ('direct_call', 'Direct Phone Call'), ('other', 'Other')], db_index=True, default='walk_in', help_text='How the client was acquired', max_length=30)),
                ('preferred_property_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('plot', 'Plot / Land'), ('rental', 'Rental Property'), ('industrial', 'Industrial')], help_text='Type of property the client is seeking or offering', max_length=30)),
                ('preferred_listing_type', models.CharField(blank=True, choices=[('sale', 'For Sale'), ('rent', 'For Rent')], help_text='Transaction preference: Sale or Rent', max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price / budget limit in currency', max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price / budget limit in currency', max_digits=14, null=True)),
                ('preferred_city', models.CharField(blank=True, db_index=True, help_text='Target city (e.g., Karachi, Lahore, Islamabad)', max_length=100)),
                ('preferred_locality', models.CharField(blank=True, help_text='Target sector, phase, or neighborhood', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Free-text agent interaction remarks and special instructions')),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Agency agent assigned to manage this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_agent', 'client_type'], name='clients_cli_assigne_f1ac91_idx'), models.Index(fields=['preferred_city', 'client_type'], name='clients_cli_preferr_f9a94e_idx'), models.Index(fields=['full_name', 'client_type'], name='clients_cli_full_na_af0b32_idx')],
            },
        ),
    ]
