# Generated by Django 5.1.15 on 2026-08-31 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('properties', '0002_remove_property_bathrooms_remove_property_bedrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4) for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag')),
                ('deal_type', models.CharField(choices=[('sale', 'Sale Transaction'), ('rent', 'Rental Lease')], db_index=True, default='sale', help_text='Transaction type: Sale or Rent', max_length=20)),
                ('deal_status', models.CharField(choices=[('negotiation', 'In Negotiation'), ('booked', 'Token / Booked'), ('in_progress', 'In Progress'), ('completed', 'Closed / Completed'), ('cancelled', 'Cancelled')], db_index=True, default='negotiation', help_text='Current transaction stage', max_length=30)),
                ('agreed_price', models.DecimalField(db_index=True, decimal_places=2, help_text='Final agreed deal amount in currency', max_digits=14)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Initial token / down payment received', max_digits=14)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate percentage (e.g. 1.00 for 1%)', max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated or fixed commission in currency', max_digits=14, null=True)),
                ('commission_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', help_text='Settlement status of agency commission', max_length=20)),
                ('is_installment', models.BooleanField(default=False, help_text='Whether this deal is structured on an installment schedule')),
                ('number_of_installments', models.PositiveSmallIntegerField(blank=True, help_text='Total number of installments (if applicable)', null=True)),
                ('installment_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually')], help_text='Payment frequency (monthly, quarterly, etc.)', max_length=20, null=True)),
                ('payment_terms_notes', models.TextField(blank=True, help_text='Terms regarding milestones, token adjustments, and installment breakdown')),
                ('deal_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date when deal terms were agreed upon')),
                ('expected_completion_date', models.DateField(blank=True, help_text='Target settlement / possession transfer date', null=True)),
                ('notes', models.TextField(blank=True, help_text='General deal notes and negotiation history')),
                ('agent', models.ForeignKey(help_text='Agent managing this deal', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client (buyer/tenant or seller/landlord) for this deal', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client')),
                ('property', models.ForeignKey(help_text='Property involved in this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='properties.property')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'deal_status'], name='deals_deal_agent_i_187332_idx'), models.Index(fields=['property', 'deal_status'], name='deals_deal_propert_4e2f66_idx'), models.Index(fields=['client', 'deal_status'], name='deals_deal_client__b941ef_idx'), models.Index(fields=['deal_type', 'deal_status'], name='deals_deal_deal_ty_6e1d1f_idx')],
            },
        ),
    ]
