# Generated by Django 5.1.15 on 2026-08-31 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date when deal terms were agreed upon'),
        ),
    ]
