# Generated by Django 5.1.15 on 2026-08-31 11:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_alter_deal_deal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4) for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Scheduled installment or payment amount in currency', max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount collected towards this payment so far', max_digits=14)),
                ('due_date', models.DateField(db_index=True, help_text='Date by which payment is scheduled/expected')),
                ('paid_date', models.DateField(blank=True, help_text='Date when payment was received/cleared', null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', help_text='Current settlement status of this payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer / Wire'), ('cheque', 'Cheque / Pay Order'), ('online', 'Online Payment / Card'), ('other', 'Other')], default='bank_transfer', help_text='Channel/mode of payment', max_length=30)),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, help_text="Sequence number (e.g. 1 for '1 of 6'); null for one-off payments", null=True)),
                ('total_installments', models.PositiveSmallIntegerField(blank=True, help_text='Total installments in the plan (e.g. 6)', null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Cheque #, bank deposit slip ID, or transaction reference', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Accountant/Agent remarks regarding this payment')),
                ('deal', models.ForeignKey(help_text='The deal transaction associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['due_date', 'installment_number'],
                'indexes': [models.Index(fields=['deal', 'installment_number'], name='payments_pa_deal_id_2b3ecb_idx'), models.Index(fields=['deal', 'payment_status'], name='payments_pa_deal_id_e6f0b8_idx'), models.Index(fields=['due_date', 'payment_status'], name='payments_pa_due_dat_629313_idx')],
            },
        ),
    ]
